function verify_in(bool upstream) {
  case net.type {
    NET_IP4: {
      if roa_check(r4) = ROA_INVALID then {
        reject "Ignore RPKI invalid ", net, " for ASN ", bgp_path.last;
      }
    }
    NET_IP6: {
      if roa_check(r6) = ROA_INVALID then {
        reject "Ignore RPKI invalid ", net, " for ASN ", bgp_path.last;
      }
    }
  }
  if (aspa_check(at, bgp_path, upstream) = ASPA_INVALID) then {
    reject "Ignore ASPA invalid ", net, " for ASN ", bgp_path.last;
  }
}
function provider_in_fun() {
  if !defined(bgp_otc) then {
    bgp_otc = bgp_path.first;
  }
  verify_in(false);
  accept;
}
function peer_in_fun() {
  if !defined(bgp_otc) then {
    bgp_otc = bgp_path.first;
  }
  if bgp_otc != bgp_path.first then reject;
  verify_in(true);
  accept;
}
function customer_in_fun() {
  if defined(bgp_otc) then {
    reject;
  }
  verify_in(true);
  accept;
}
filter complex_in {
  verify_in(false);
  accept;
}
function provider_out_fun() {
  if defined(bgp_otc) then {
    reject;
  }
  accept;
}
function peer_out_fun() {
  if defined(bgp_otc) then {
    reject;
  }
  bgp_otc = self_as;
  accept;
}
function customer_out_fun() {
  if !defined(bgp_otc) then {
    bgp_otc = self_as;
  }
  accept;
}
filter provider_in {
  provider_in_fun();
}
filter peer_in {
  peer_in_fun();
}
filter customer_in {
  customer_in_fun();
}
filter provider_out {
  provider_out_fun();
}
filter peer_out {
  peer_out_fun();
}
filter customer_out {
  customer_out_fun();
}
